# Football Pipeline Configuration
# This file contains all configurable settings for the pipeline

# Processing Configuration
processing:
  # Which layers to process (true/false)
  bronze: true
  silver: false
  gold: false
  
  # Which source to process (null for all sources)
  # Options: "open_data", "j1_league", or null for all
  source: null
  
  # Error handling behavior
  fail_fast: true  # If true, stop pipeline on first error
  continue_on_error: false  # If true, continue processing other sources on error

# Logging Configuration
logging:
  console_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_level: "DEBUG"

# Directory Structure (relative to PROJECT_ROOT)
directories:
  data: "data"
  logs: "logs"
  landing: "data/landing"
  bronze: "data/bronze"
  silver: "data/silver"
  gold: "data/gold"


