import polars as pl

# J1 League matches schema - based on StatsBomb structure
J1_LEAGUE_MATCHES_SCHEMA = {
    "match_id": pl.Int64,
    "match_date": pl.String,
    "kick_off": pl.String,
    "home_score": pl.Int64,
    "away_score": pl.Int64,
    "behind_closed_doors": pl.Boolean,
    "neutral_ground": pl.Boolean,
    "collection_status": pl.String,
    "play_status": pl.String,
    "match_status": pl.String,
    "match_status_360": pl.String,
    "last_updated": pl.String,
    "last_updated_360": pl.String,
    "match_week": pl.Int64,
    "competition_competition_id": pl.Int64,
    "competition_country_name": pl.String,
    "competition_competition_name": pl.String,
    "season_season_id": pl.Int64,
    "season_season_name": pl.String,
    "home_team_home_team_id": pl.Int64,
    "home_team_home_team_name": pl.String,
    "home_team_home_team_gender": pl.String,
    "home_team_home_team_youth": pl.Boolean,
    "home_team_country_id": pl.Int64,
    "home_team_country_name": pl.String,
    "away_team_away_team_id": pl.Int64,
    "away_team_away_team_name": pl.String,
    "away_team_away_team_gender": pl.String,
    "away_team_away_team_youth": pl.Boolean,
    "away_team_country_id": pl.Int64,
    "away_team_country_name": pl.String,
    "metadata_data_version": pl.String,
    "metadata_shot_fidelity_version": pl.String,
    "metadata_xy_fidelity_version": pl.String,
    "competition_stage_id": pl.Int64,
    "competition_stage_name": pl.String,
    "stadium_id": pl.Int64,
    "stadium_name": pl.String,
    "stadium_country_id": pl.Int64,
    "stadium_country_name": pl.String,
    "referee_id": pl.Int64,
    "referee_name": pl.String,
    "referee_country_id": pl.Int64,
    "referee_country_name": pl.String,
    
    # Manager information (can be multiple, flattened)
    "home_team_managers_id": pl.Int64,
    "home_team_managers_name": pl.String,
    "home_team_managers_dob": pl.String,
    "home_team_managers_country_id": pl.Int64,
    "home_team_managers_country_name": pl.String,
    "away_team_managers_id": pl.Int64,
    "away_team_managers_name": pl.String,
    "away_team_managers_dob": pl.String,
    "away_team_managers_country_id": pl.Int64,
    "away_team_managers_country_name": pl.String,
} 