import polars as pl

EVENTS_SCHEMA = {
    "id": pl.String,
    "index": pl.Int64,
    "period": pl.Int64,
    "timestamp": pl.String,  # Skip type validation for timestamps
    "minute": pl.Int64,
    "second": pl.Int64,
    "possession": pl.Int64,
    "duration": pl.Float64,
    "type_id": pl.Int64,
    "type_name": pl.String,
    "possession_team_id": pl.Int64,
    "possession_team_name": pl.String,
    "play_pattern_id": pl.Int64,
    "play_pattern_name": pl.String,
    "team_id": pl.Int64,
    "team_name": pl.String,
    "tactics_formation": pl.Float64,
    "related_events": pl.List,  # Changed from String to Object for lists
    "location": pl.List,  # Changed from String to Object for arrays
    "player_id": pl.Int64,
    "player_name": pl.String,
    "position_id": pl.Int64,
    "position_name": pl.String,
    "pass_recipient_id": pl.Int64,
    "pass_recipient_name": pl.String,
    "pass_length": pl.Float64,
    "pass_angle": pl.Float64,
    "pass_height_id": pl.Int64,
    "pass_height_name": pl.String,
    "pass_end_location": pl.List,  # Changed from String to Object for arrays
    "pass_body_part_id": pl.Int64,
    "pass_body_part_name": pl.String,
    "pass_type_id": pl.Int64,
    "pass_type_name": pl.String,
    "under_pressure": pl.Boolean,
    "carry_end_location": pl.List,  # Changed from String to Object for arrays
    "pass_outcome_id": pl.Int64,
    "pass_outcome_name": pl.String,
    "ball_receipt_outcome_id": pl.Int64,
    "ball_receipt_outcome_name": pl.String,
    "pass_assisted_shot_id": pl.String,
    "pass_shot_assist": pl.Boolean,
    "pass_through_ball": pl.Boolean,
    "pass_technique_id": pl.Int64,
    "pass_technique_name": pl.String,
    "dribble_outcome_id": pl.Int64,
    "dribble_outcome_name": pl.String,
    "shot_statsbomb_xg": pl.Float64,
    "shot_end_location": pl.List,  # Changed from String to Object for arrays
    "shot_key_pass_id": pl.String,
    "shot_body_part_id": pl.Int64,
    "shot_body_part_name": pl.String,
    "shot_technique_id": pl.Int64,
    "shot_technique_name": pl.String,
    "shot_type_id": pl.Int64,
    "shot_type_name": pl.String,
    "shot_outcome_id": pl.Int64,
    "shot_outcome_name": pl.String,
    "goalkeeper_end_location": pl.List,  # Changed from String to Object for arrays
    "goalkeeper_position_id": pl.Int64,
    "goalkeeper_position_name": pl.String,
    "goalkeeper_type_id": pl.Int64,
    "goalkeeper_type_name": pl.String,
    "pass_cross": pl.Boolean,
    "counterpress": pl.Boolean,
    "duel_type_id": pl.Int64,
    "duel_type_name": pl.String,
    "duel_outcome_id": pl.Int64,
    "duel_outcome_name": pl.String,
    "goalkeeper_outcome_id": pl.Int64,
    "goalkeeper_outcome_name": pl.String,
    "ball_recovery_recovery_failure": pl.Boolean,
    "pass_switch": pl.Boolean,
    "shot_first_time": pl.Boolean,
    "pass_goal_assist": pl.Boolean,
    "dribble_nutmeg": pl.Boolean,
    "interception_outcome_id": pl.Int64,
    "interception_outcome_name": pl.String,
    "pass_aerial_won": pl.Boolean,
    "dribble_overrun": pl.Boolean,
    "pass_backheel": pl.Boolean,
    "goalkeeper_technique_id": pl.Int64,
    "goalkeeper_technique_name": pl.String,
    "goalkeeper_body_part_id": pl.Int64,
    "goalkeeper_body_part_name": pl.String,
    "pass_deflected": pl.Boolean,
    "block_deflection": pl.Boolean,
    "substitution_outcome_id": pl.Int64,
    "substitution_outcome_name": pl.String,
    "substitution_replacement_id": pl.Int64,
    "substitution_replacement_name": pl.String,
    "shot_one_on_one": pl.Boolean,
    "foul_committed_advantage": pl.Boolean,
    "foul_won_advantage": pl.Boolean,
    "injury_stoppage_in_chain": pl.Boolean,
    "foul_committed_offensive": pl.Boolean,
    "foul_won_defensive": pl.Boolean,
    "bad_behaviour_card_id": pl.Int64,
    "bad_behaviour_card_name": pl.String,
    "ball_recovery_offensive": pl.Boolean,
    "tactics_lineup_jersey_number": pl.Int64,
    "shot_freeze_frame_location": pl.List,  # Changed from String to Object for arrays
    "shot_freeze_frame_teammate": pl.Boolean,
    "tactics_lineup_player_id": pl.Int64,
    "tactics_lineup_player_name": pl.String,
    "tactics_lineup_position_id": pl.Int64,
    "tactics_lineup_position_name": pl.String,
    "shot_freeze_frame_player_id": pl.Int64,
    "shot_freeze_frame_player_name": pl.String,
    "shot_freeze_frame_position_id": pl.Int64,
    "shot_freeze_frame_position_name": pl.String,
    "x": pl.Float64,
    "y": pl.Float64,
    "end_x": pl.Float64,
    "end_y": pl.Float64,
    "possession_event_count": pl.Int64,  # Changed from String to Int64
    "possession_pass_count": pl.Int64,  # Changed from String to Int64
    "possession_player_count": pl.Int64,  # Changed from String to Int64
    "possession_duration": pl.Float64,  # Changed from Int64 to Float64 for seconds
    "total_xG": pl.Float64,
    
    # Adding common extra columns found in the data
    "clearance_left_foot": pl.Boolean,
    "clearance_right_foot": pl.Boolean,
    "clearance_head": pl.Boolean,
    "clearance_other": pl.Boolean,
    "clearance_body_part_id": pl.Int64,
    "clearance_body_part_name": pl.String,
    "clearance_aerial_won": pl.Boolean,
    
    "50_50_outcome_id": pl.Int64,
    "50_50_outcome_name": pl.String,
    
    "block_offensive": pl.Boolean,
    "block_save_block": pl.Boolean,
    
    "foul_committed_type_id": pl.Int64,
    "foul_committed_type_name": pl.String,
    "foul_committed_card_id": pl.Int64,
    "foul_committed_card_name": pl.String,
    
    "pass_inswinging": pl.Boolean,
    "pass_outswinging": pl.Boolean,
    "pass_cut_back": pl.Boolean,
    "pass_no_touch": pl.Boolean,
    "pass_straight": pl.Boolean,
    "pass_miscommunication": pl.Boolean,
    
    "shot_deflected": pl.Boolean,
    "shot_aerial_won": pl.Boolean,
    "shot_open_goal": pl.Boolean,
    "shot_redirect": pl.Boolean,
    
    "miscontrol_aerial_won": pl.Boolean,
    "dribble_no_touch": pl.Boolean,
    "goalkeeper_punched_out": pl.Boolean,
    
    "off_camera": pl.Boolean,
    "out": pl.Boolean,
    
    # NEW: Adding missing columns from schema validation warnings
    "goalkeeper_shot_saved_off_target": pl.Boolean,
    "shot_saved_off_target": pl.Boolean,
    "goalkeeper_shot_saved_to_post": pl.Boolean,
    "shot_saved_to_post": pl.Boolean,
    "goalkeeper_success_in_play": pl.Boolean,
    "half_start_late_video_start": pl.Boolean,
    "foul_committed_penalty": pl.Boolean,
    "foul_won_penalty": pl.Boolean,
}