import polars as pl

LINEUPS_SCHEMA = {
    "player_id": pl.Int64,
    "player_name": pl.String,
    "player_nickname": pl.String,
    "jersey_number": pl.Int64,
    "match_id": pl.Int64,
    "team_id": pl.Int64,
    "country_id": pl.Int64,
    "country_name": pl.String,
    "cards": pl.String,
    "cards_time": pl.String,
    "cards_card_type": pl.String,
    "cards_reason": pl.String,
    "cards_period": pl.Int64,
    "positions_position_id": pl.Int64,
    "positions_position": pl.String,
    "positions_from": pl.String,
    "positions_to": pl.String,
    "positions_from_period": pl.Int64,
    "positions_to_period": pl.Int64,
    "positions_start_reason": pl.String,
    "positions_end_reason": pl.String,
}